// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoStringAvg.proto

package com.whzl.mengbi.chat;

public final class ProtoStringAvg {
  private ProtoStringAvg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface strAvgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:strAvg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes strs = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getStrsList();
    /**
     * <code>repeated bytes strs = 1;</code>
     */
    int getStrsCount();
    /**
     * <code>repeated bytes strs = 1;</code>
     */
    com.google.protobuf.ByteString getStrs(int index);
  }
  /**
   * Protobuf type {@code strAvg}
   */
  public  static final class strAvg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:strAvg)
      strAvgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use strAvg.newBuilder() to construct.
    private strAvg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private strAvg() {
      strs_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private strAvg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                strs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              strs_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          strs_ = java.util.Collections.unmodifiableList(strs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoStringAvg.internal_static_Show_strAvg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoStringAvg.internal_static_Show_strAvg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoStringAvg.strAvg.class, ProtoStringAvg.strAvg.Builder.class);
    }

    public static final int STRS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> strs_;
    /**
     * <code>repeated bytes strs = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getStrsList() {
      return strs_;
    }
    /**
     * <code>repeated bytes strs = 1;</code>
     */
    public int getStrsCount() {
      return strs_.size();
    }
    /**
     * <code>repeated bytes strs = 1;</code>
     */
    public com.google.protobuf.ByteString getStrs(int index) {
      return strs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < strs_.size(); i++) {
        output.writeBytes(1, strs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < strs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strs_.get(i));
        }
        size += dataSize;
        size += 1 * getStrsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoStringAvg.strAvg)) {
        return super.equals(obj);
      }
      ProtoStringAvg.strAvg other = (ProtoStringAvg.strAvg) obj;

      boolean result = true;
      result = result && getStrsList()
          .equals(other.getStrsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStrsCount() > 0) {
        hash = (37 * hash) + STRS_FIELD_NUMBER;
        hash = (53 * hash) + getStrsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoStringAvg.strAvg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoStringAvg.strAvg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoStringAvg.strAvg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoStringAvg.strAvg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoStringAvg.strAvg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoStringAvg.strAvg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoStringAvg.strAvg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code strAvg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:strAvg)
        ProtoStringAvg.strAvgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoStringAvg.internal_static_Show_strAvg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoStringAvg.internal_static_Show_strAvg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoStringAvg.strAvg.class, ProtoStringAvg.strAvg.Builder.class);
      }

      // Construct using ProtoStringAvg.strAvg.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        strs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoStringAvg.internal_static_Show_strAvg_descriptor;
      }

      public ProtoStringAvg.strAvg getDefaultInstanceForType() {
        return ProtoStringAvg.strAvg.getDefaultInstance();
      }

      public ProtoStringAvg.strAvg build() {
        ProtoStringAvg.strAvg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoStringAvg.strAvg buildPartial() {
        ProtoStringAvg.strAvg result = new ProtoStringAvg.strAvg(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          strs_ = java.util.Collections.unmodifiableList(strs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.strs_ = strs_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoStringAvg.strAvg) {
          return mergeFrom((ProtoStringAvg.strAvg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoStringAvg.strAvg other) {
        if (other == ProtoStringAvg.strAvg.getDefaultInstance()) return this;
        if (!other.strs_.isEmpty()) {
          if (strs_.isEmpty()) {
            strs_ = other.strs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStrsIsMutable();
            strs_.addAll(other.strs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoStringAvg.strAvg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoStringAvg.strAvg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> strs_ = java.util.Collections.emptyList();
      private void ensureStrsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          strs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(strs_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getStrsList() {
        return java.util.Collections.unmodifiableList(strs_);
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public int getStrsCount() {
        return strs_.size();
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public com.google.protobuf.ByteString getStrs(int index) {
        return strs_.get(index);
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public Builder setStrs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrsIsMutable();
        strs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public Builder addStrs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrsIsMutable();
        strs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public Builder addAllStrs(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureStrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes strs = 1;</code>
       */
      public Builder clearStrs() {
        strs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:strAvg)
    }

    // @@protoc_insertion_point(class_scope:strAvg)
    private static final ProtoStringAvg.strAvg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoStringAvg.strAvg();
    }

    public static ProtoStringAvg.strAvg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<strAvg>
        PARSER = new com.google.protobuf.AbstractParser<strAvg>() {
      public strAvg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new strAvg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<strAvg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<strAvg> getParserForType() {
      return PARSER;
    }

    public ProtoStringAvg.strAvg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Show_strAvg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Show_strAvg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024protoStringAvg.proto\022\004Show\"\026\n\006strAvg\022\014" +
      "\n\004strs\030\001 \003(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Show_strAvg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Show_strAvg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Show_strAvg_descriptor,
        new String[] { "Strs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
